config/routes.rb
EjemploDeviseCancan::Application.routes.draw do
  #get "home/index"

  #match '/' => 'home#index', :as => :root
  devise_for :users

  resources :users
  resources :roles

  match 'comprobar_invitado'=> 'comprobar_invitado#index', :as=> 'comprobar_invitado'
  match 'comprobar_admin'=> 'comprobar_admin#index', :as=> 'comprobar_admin'
  match 'comprobar_operator'=> 'comprobar_operator#index', :as=> 'comprobar_operator'
  root to: 'home#index'




end

app/models/ability.rb
#Dar roles a Cancan para poder interactuar con Devise
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    if user.role? :administrator  #role de administrador con permiso para cualquier controlador
      can :manage, :all
    elsif user.role? :operator
      can :manage, :comprobar_operator #role de operador con permiso para el CRUD del controlador ComprobarOperator(comprobar_operator_controller.rb)
      can [:index], :comprobar_invitado #tambien puede pasar al index de ComprobarInvitado#index
    else
      can [:index], :comprobar_invitado             #role usuario invitado (solo puede acceder a ComprobarInvitado#index)
    end
  end
end
#can puede tener  :create, :read, :update, :delete, and :manage por defecto. Tambien puedes crear los tuyos. Mirar documentacion CanCan
#otra manera de crear inicialize. =begin / =end son bloque de comentarios en ruby
=begin
  def initialize(user)
    can :manage, :all if user.is_administrator?
  end
=end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :role_ids

  has_and_belongs_to_many :roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Debes identificarte correctamente. Acceso denegado."
    session[:user_return_to] = request.url
    redirect_to root_path
  end

end

app/controllers/comprobar_admin_controller.rb
class ComprobarAdminController < ApplicationController
  #before_filter :authenticate_user!   #sin este filtro no hay autenticacion. Se debe poner en todos los controllers
  #load_and_authorize_resource  #se usa si este controlador tiene un modelo y este no tiene
  authorize_resource :class => false
  def index
  end

end

app/controllers/comprobar_invitado_controller.rb
class ComprobarInvitadoController < ApplicationController
  #before_filter :authenticate_user!   #sin este filtro no hay autenticacion. Se debe poner en todos los controllers
  #load_and_authorize_resource #se usa si este controlador tiene un modelo y este no tiene
  authorize_resource :class => false
  def index
  end

end

app/controllers/comprobar_operator_controller.rb
class ComprobarOperatorController < ApplicationController
  #before_filter :authenticate_user!   #sin este filtro no hay autenticacion. Se debe poner en todos los controllers
  #load_and_authorize_resource  ##se usa si este controlador tiene un modelo y este no tiene
  authorize_resource :class => false
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @current_method = "new"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comprobar_admin_helper.rb
module ComprobarAdminHelper
end

app/helpers/comprobar_invitado_helper.rb
module ComprobarInvitadoHelper
end

app/helpers/comprobar_operator_helper.rb
module ComprobarOperatorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/comprobar_admin/index.html.erb
<h1>Area de Administrator</h1>
<p>Find me in app/views/comprobar_admin/index.html.erb</p>

app/views/comprobar_invitado/index.html.erb
<h1>Area de Invitado</h1>
<p>Find me in app/views/comprobar_invitado/index.html.erb</p>

app/views/comprobar_operator/index.html.erb
<h1>Area de Operator</h1>
<p>Find me in app/views/comprobar/index.html.erb</p>

app/views/home/index.html.erb
<h1>Area de Home (inicio)</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EjemploDeviseCancan</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Area Admin', comprobar_admin_path%> ||
<%= link_to 'Area Operator', comprobar_operator_path%> ||
<%= link_to 'Area Invitado', comprobar_invitado_path%> ---------------->
<%= link_to 'CRUD de Usuarios (en editar otorgas roles a un usuario)', users_path%> ||
<%= link_to 'CRUD de Roles', roles_path%> |----------------|

<%= link_to 'Salir sesion', destroy_user_session_path, :method => :delete %>
<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

<div id="user_nav">
  <% if user_signed_in? %>
      Login como <%= current_user.email %>. Not you?
  <% else %>
      -No logueado-
  <% end %>
</div>

<br/><br/>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
    <% if @current_method == "new" %>
        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation %>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :role_ids, "Roles asociados " %>
      <%= f.collection_select(:role_ids, Role.all, :id,:name,  {:selected => @user.role_ids, :include_blank => true}, {:multiple => true})%>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Username</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Roles de este usuario:</b>
<% if @user.roles.empty? %>
    --  no hay --
<%else%>
    <% @user.roles.each do |role| %>
        <li><%= role.name %></br></li>
    <%end%>
<%end%>
</p>

</br></br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>